### ISSUE TITLE
Redundant Semicolon

### ISSUE THREAD

**Issue by HpLightcorner** [kmilo17pet/QuarkTS#25]
Hi,

**Compiler**: MSVC 

I think I found a quick-fix bug... At least MSVC (with standard checks) fails to compile.

The semicolon in line 85 and 86 when calling the Macro `_qSM_HANDLER_FIELDS` to define const/non-const is redundant
https://github.com/kmilo17pet/QuarkTS/blob/b15628dc05c148efa3ab414646abb140053bb50f/include/qfsm.h#L85
as the Macro itself defines the semicolon at the end of struct-definition:
https://github.com/kmilo17pet/QuarkTS/blob/b15628dc05c148efa3ab414646abb140053bb50f/include/qfsm.h#L68-L75

So I suggest to either remove the semicolon after calling the macro or in the macro itself.
I think I won't open a PR for this one as its just one symbol to remove...

**Comment by kmilo17pet** [comment]
fixed! as always @HpLightcorner , thanks for your feedback
