### ISSUE TITLE
Arduino compile error

### ISSUE THREAD

**Issue by NickNifontov** [kmilo17pet/QuarkTS#29]
In file included from qtasks.h:18:0,
                 from qkernel.h:7,
                 from QuarkTS.h:43,
qatcli.h:99:16: warning: '_qATCLI_ControlBlock_s::_qATCLI_Private_s' has a field '_qATCLI_ControlBlock_s::_qATCLI_Private_s::Input' whose type has no linkage [-Wsubobject-linkage]
         struct _qATCLI_Private_s{
                ^~~~~~~~~~~~~~~~~

Can you help?

**Comment by NickNifontov** [comment]
#include "QuarkTS.h"

void setup() {
  // put your setup code here, to run once:
  qOS_Setup( NULL , NULL );
  qOS_Run();
}

void loop() {
  // put your main code here, to run repeatedly:
}

**Comment by kmilo17pet** [comment]
appears to be a warning, not an error. However, I'll give it a look.

**Comment by kmilo17pet** [comment]
fixed on https://github.com/kmilo17pet/QuarkTS/commit/c200bbf752b5da937e54e1777135790bfdc890f9
