### ISSUE TITLE
qATCLI minor optimization

### ISSUE THREAD

**Issue by kmilo17pet** [kmilo17pet/QuarkTS#31]
https://github.com/kmilo17pet/QuarkTS/blob/1af0462d9e6e7c5fb20c41978ad47a37a8e9420a/qatcli.c#L264

Replace
`if ( strstr( cmd, Command->Text ) == cmd ) `

with

`if ( 0 == strncmp( cmd, Command->Text, Command->qPrivate.CmdLen ) ) `

This will improve speed and it will also be safe.

need to be tested on real scenarios

**Comment by thejbte** [comment]
ATCLI is tested in stm32f411, it works correctly with of command type test, para, read y act.

view attachment image.

![realScenarioAtcliInStm32f411](https://user-images.githubusercontent.com/17997755/135375936-32241c7a-10e0-4f39-87b9-004905d6b9d4.png)

**Comment by kmilo17pet** [comment]
ready on https://github.com/kmilo17pet/QuarkTS/commit/7e45572151da88301b270f5f29d56b6a3b952f53
