### ISSUE TITLE
Bug in atcli

### ISSUE THREAD

**Issue by thejbte** [kmilo17pet/QuarkTS#33]
Bug in ATCLI when sending any command with CR that is not in the list of subscribed commands. this error occurs before a valid command is sent for the first time, after sending the valid command it does not occur.

example:

Error:
1. Running firmware for the first time
2. send "at\r"
3. segmentation fault

1. Running firmware for the first time
2. send "anything\r"
3. segmentation fault

No error:
1. Running firmware for the first time
2. send "at+help\r" , this a command is part of the subscribed command list
3. OK

**Comment by kmilo17pet** [comment]
fixed on v7.1.6
