### ISSUE TITLE
_QTRACE_KERNEL not defined when trace variables are not used

### ISSUE THREAD

**Issue by IanSim2012** [kmilo17pet/QuarkTS#34]
Hi QuarkTS Team,
first of all I would like you to thank you very much for this work, I'm just playing around with it and I found it very interesting!

I'm using a PSoC4M series microcontroller from Infineon (ex Cypress), I configured the `qconfig.h` and built a simple project.
However, I got some implicit declaration warnings and undefined reference errors related to the `_QTRACE_KERNEL` definition.

I configured the `qconfig.h` to not use the trace variables:
```c
#define Q_TRACE_VARIABLES           ( 0 )
```

Looking at the code, in this way the  `_QTRACE_KERNEL` is never defined, but the code actually calls this function.
I solved the problem by adding the following statement into the `qtrace.h` file within the proper conditional directive: 
```c
#define _QTRACE_KERNEL( msg, id, obj )  do {} while (0)
```
Is this a bug or I'm missing something?

Thank you very much!
Simone

**Comment by kmilo17pet** [comment]
Thanks @IanSim2012. Yep, 
it is indeed a bug. It is already fixed in the latest release
