### ISSUE TITLE
Issues in qstimers.c

### ISSUE THREAD

**Issue by Cages-hub** [kmilo17pet/QuarkTS#40]
1) The documentation and code do not match

https://github.com/kmilo17pet/QuarkTS/blob/e8da1ea3caa8dad87c2336576d2bb8a1fc75532d/qstimers.c#L44

qSTimer_FreeRun() when the time expires, the STimer gets armed immediately taking the specified time. This implies it should call qSTimer_Reload() if STimer expires not qSTimer_Disarm( t )

2) qSTimer_Remaining() does not check if elapsed time is greater than t->tv  before subtracting. It should return 0 if qSTimer_Elapsed( t ) is greater than t->tv

https://github.com/kmilo17pet/QuarkTS/blob/e8da1ea3caa8dad87c2336576d2bb8a1fc75532d/qstimers.c#L87

**Comment by kmilo17pet** [comment]
hi @Cages-hub , thanks for your notes
p1. in effect, this saves us a tick of the clock. (will be reviewed and tested)
p2. By design, the elapsed time will never be greater than the set time. (no actions)

**Comment by kmilo17pet** [comment]
fixed https://github.com/kmilo17pet/QuarkTS/commit/0ea32890b79eaa7745a412fe5d29fe3e29144379
