### ISSUE TITLE
feature: Add Pub/Sub interface for qSM_Signal_t (qSM_t)

### ISSUE THREAD

**Issue by MichalRostekRostkowski** [kmilo17pet/QuarkTS#45]
Currently signals can only be sent to particualar qSM_t HSMs. That forces some level of coupling.
HSM that sends signals has to know which HSM is interested in receiving it.

Adding Pub/Sub interafce would allow HSMs to declare which signals it wants to receive without mentioning
any other HSM. That would completly decouple HSMs.

Draft of such an interface can be find here: https://github.com/MichalRostekRostkowski/QuarkTS/pull/2

**Comment by kmilo17pet** [comment]
@ManuelPosada @thejbte ,  what you think about integrating this pattern to the FSM module?
I think the approach proposed by Michal will be simplier to tackle  tackled if is handled as a built-in feature of the qFSM.

**Comment by MichalRostekRostkowski** [comment]
Hello guys,
any thoughts on this?

**Comment by kmilo17pet** [comment]
taking a look...

**Comment by kmilo17pet** [comment]
https://github.com/kmilo17pet/QuarkTS/commit/79d9626efea46501e42db30bf29c0fe4fa1bbd13
Thanks @MichalRostekRostkowski
