### ISSUE TITLE
ScXML - automatic code generation

### ISSUE THREAD

**Issue by MichalRostekRostkowski** [kmilo17pet/QuarkTS#47]
Consider creating tool that consumes ScXML file as input and generates *.c and *.h files with application structure using QuarkTS as base. ScXML files would be generated by external (already existing) tools.
Creating HSMs in visual tools is easier and faster then writing them by hand. These kind of tools also provide possibility to test designs before compiling and programming destination devices.

Very good (and free) tool is ScxmlEditor created by Alex Zhornyak - https://github.com/alexzhornyak/SCXML-tutorial

**Comment by kmilo17pet** [comment]
will be on the roadmap, on hold for now
