### ISSUE TITLE
Bug in qIOUtil_XtoU32 function

### ISSUE THREAD

**Issue by MichalRostekRostkowski** [kmilo17pet/QuarkTS#53]
File: src/quarkts/qioutils.c
Function: qIOUtil_XtoU32()
Currently: when procedure is parsing A-F characters in the string value 75u is subtracted from xByte value.
eg.
  string: "A"
  result: "A" = 65u (dec), 65u - 75u = -10u

Should be: subtract value 55u instead of 75u
eg.
  string: "A"
  result: "A" = 65 (dec), 65 - 55 = 10

**Comment by kmilo17pet** [comment]
fixed!
