### ISSUE TITLE
_qTrace_Kernel

### ISSUE THREAD

**Issue by billiumbuck** [kmilo17pet/QuarkTS#55]
I just updated and got compile error (for STM32 using cubeIDE)

"undefined reference to _qTrace_Kernel"

I added this

#define Q_TRACE_KERNEL_AND_MODULES  ( 0 )       /**< Experimental*/

to qconfig.h

Got round it by commenting out all the _qTrace_Kernel lines mainly in qkernel.c

Have I missed something?

Thanks for your work, it is  great for me and easy to add to projects, I've used it on AVR and PiPico.

**Comment by kmilo17pet** [comment]
fixed typo! closing issue
